### PR TITLE
Added loading dialog

### PR DESCRIPTION
**Pull request by codeDamon**
Issue #9 Solved

# Prosposed Changes
- Added loading dialog
- With a delay of 2 seconds

Now when user clicks on 'Get Vendors' button, a loading dialog pops up and after a delay of 2 sec recycleData() is called.

### CODE REVIEW

**Comment by plazzy99** [comment]
@codeDamon your pull request stands invalid as the issue was not assigned to you.
If in case the participant with the assigned issue takes his assignment back then only your pr will be considered.

Also pr are only accepted in the develop branch.

**Comment by codeDamon** [comment]
Okay, No problem. 
The person assigned with the issue has not completed this basic issue since 14 days of his allotment. Therefore, I made the pull request.
Talking about not creating dev-branch for pull request - I am sorry for that. 
I can create a branch and then create PR if you want me to do so.

**Comment by plazzy99** [comment]
@codeDamon you can comment on the issue and ask assignee if he is not able to work then you can take over

**Review by plazzy99 — APPROVED** [review]
👍🏻 
LGTM
@codeDamon share a video of the loading dialog by recording the screen.

**Comment by codeDamon** [comment]
Demo of the loading dialog
Loading_dialog_demo_recording

**Pull request merged**
