### PR TITLE
bottom nav

### PR DESCRIPTION
**Pull request by spacemonkey1101**
# Related Issue
-  #2 

# Additional Info
- Once you tell me that I am in the right direction, I'll move further

### CODE REVIEW

**Review by plazzy99 — CHANGES_REQUESTED** [review]
First make a main activity which contains the bottom nav
Then convert  the 3 actvity as fragment : Home,  Covid data , precaution 
then work that like a bottom nav

**Comment by spacemonkey1101** [comment]
made the changes

**Comment by plazzy99** [comment]
@spacemonkey1101 all changes look good to me.

Just to cross-check please share me an apk in the discord channel.

**Review by plazzy99 — APPROVED** [review]
👍🏻

**Pull request merged**
